# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.CharField(choices=[('sms', 'sms'), ('lms', 'lms'), ('mms', 'mms'), ('ata', 'ata')], max_length=3)),
                ('msg_getter', models.IntegerField()),
                ('msg_sender', models.IntegerField()),
                ('msg_text', models.TextField()),
            ],
        ),
    ]
