# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smssend',
            name='msg_getter',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='smssend',
            name='msg_sender',
            field=models.CharField(default='01029953874', max_length=20),
        ),
        migrations.AlterField(
            model_name='smssend',
            name='msg_type',
            field=models.CharField(choices=[('sms', 'sms'), ('lms', 'lms'), ('mms', 'mms'), ('ata', 'ata')], default='sms', max_length=3),
        ),
    ]
