# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0002_auto_20170628_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smssend',
            name='msg_type',
            field=models.CharField(choices=[('sms', 'sms')], default='sms', max_length=3),
        ),
    ]
